### ISSUE TITLE
delimiter will not be used, but it looks like ";" is hard coded

### ISSUE THREAD

**Issue by aisbergde** [brianbonk/GenerateFormatFile#1]
it is possible to use a delimiter as parameter, but it will not used.
it looks like ";" is hard coded as delimeter

look at the call:
            //do magic stuff
            var doc = HandleFile.GenerateXMLFile(path, filename, delimiter);
            doc.Save(new StreamWriter(File.OpenWrite(path + outputfile)));

but then look into the called cs
namespace Rehfeld.Common
{
    public class HandleFile
    {
        public static XDocument GenerateXMLFile(string path, string filename, string **dataarea**)

**dataarea** is not used in the code
but it looks like here the ";" is hard coded:

string[] values = reader.ReadLine().Replace(@"""", @"").**Split(';')**;

But the idea of this FormatFile generator is great!

**Comment by JasonSTX** [comment]
Since this is still waiting, I will leave this note here:

edit the common.cs and change line 13 from:
string[] values = reader.ReadLine().Replace(@"""", @"").Split(';');
to:
string[] values = reader.ReadLine().Replace(@"""", @"").Split(delimiter.ToCharArray()[0]);

Then recompile.  It does assume you have a single character as the delimiter.

**Comment by brianbonk** [comment]
So sorry - I haven't gotten any notifications on this project - ever.... For some reason
I've just apporved the changes and merged the files...
